# Generated by Django 5.1.4 on 2025-01-26 20:25

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Meeting Title')),
                ('attendee', models.CharField(max_length=120, verbose_name='Attendee Name')),
                ('url', models.CharField(blank=True, max_length=120, null=True, verbose_name='Meeting URL')),
                ('date', models.DateField(verbose_name='Meeting Date')),
                ('time', models.TimeField(default=datetime.time(12, 0), verbose_name='Meeting Start Time')),
                ('description', models.TextField(blank=True)),
                ('duration', models.PositiveIntegerField(blank=True, choices=[(30, "30'"), (45, "45'"), (60, "60'"), (75, "75'"), (90, "90'")], default=30, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('semester', models.CharField(max_length=20)),
                ('num_meetings', models.PositiveIntegerField()),
                ('majority_day', models.CharField(choices=[('monday', 'Δευτέρα'), ('tuesday', 'Τρίτη'), ('wednesday', 'Τετάρτη'), ('thursday', 'Πέμπτη'), ('friday', 'Παρασκευή')], max_length=10)),
                ('majority_time', models.CharField(choices=[('08:00-10:00', '08:00-10:00'), ('10:00-12:00', '10:00-12:00'), ('12:00-14:00', '12:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00')], max_length=11)),
                ('avg_duration', models.CharField(choices=[('15', 'Έως 15 λεπτά'), ('30', 'Έως 30 λεπτά'), ('60', 'Έως 60 λεπτά'), ('>60', 'Πάνω από 60 λεπτά')], max_length=5)),
                ('topics', models.JSONField()),
                ('custom_topic', models.TextField(blank=True, null=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings_with_students', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
